apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: 203576913699.dkr.ecr.us-east-1.amazonaws.com/maxrepo:maxcell-v1
        ports:
        - containerPort: 80